### ISSUE TITLE
Luis Soto Medina

### ISSUE THREAD

**Issue by cguz** [cguz/cguz.github.io#1]
Title: 

Objective: Detectar sentimientos a partir de un texto -> mapear el sentimiento con una coordenada -> pasar la coordenada como input al generador de musica

luissoto.personal@gmail.com

Title: Desarrollo de una AI generativa de audio

Github: https://github.com/luissotomedina/Generative_Music_AI
Latex:

**Comment by cguz** [comment]
# Master Guidance

This guide outlines the steps for completing your Master's Dissertation, based on personal experience. 

- [x] Download the word/latex template (check in the virtual aula)
- [x] Generate a shared link and send it to me
- [x] Create a GitHub repository
- [x] Share Github or Latex with research@cguz.org

## Phase 1: Foundation

All the following should be written directly on the word/latex template

- [ ] Use APA or IEEE referencing style
- [x] Define topic and title
- [ ] The title is specific and directly related to the content of the work. The title should provide a clear idea of the topics covered and the conclusions reached
- [ ] Create initial document structure with chapters and sections
- [ ] Section Objectives: Write General and specific objectives (max 1.5 pages)
- [x] Section State of the Art: 
  - [ ] Research and write a comprehensive literature review 
  - [ ] Related works. 
    - For each related work:
      - [x] Include References
      - [x] Used techniques
      - [x] Summarize used techniques, dataset, and obtained results
      - [x] Identify the related work's GitHub repository (if available)
      - [x] Identify dataset
  - [ ] Used techniques: Explain the most relevant techniques found in the related works.

## Phase 2: Development

- [ ] Select two or three techniques identified in Phase 1
- Section development:
  - [ ] Architecture Design
    - [ ] Define the architecture design for your solution
    - [ ] Write the architecture design
    - [ ] Implement the architecture design  
  - [ ] Feature selection: Introduce all variables used in the study. And explain the reasons for excluding any variables from the analysis, if applicable.
  - [ ] Justify each chosen technique, explaining its relevance and suitability for the problem at hand.
  - [ ] Include a correlation analysis of the variables, accompanied by an easily interpretable correlation matrix.
  - [ ] Refine section development, if necessary.
- [ ] Section Introduction: Start writting
- [ ] Section Results:
  - [ ] Include any training/evaluation image or table (Do not write the results yet).
- [ ] Do not include the source code in the appendices, instead share the Github link in the document.

## Phase 3: Results

- [ ] Write Section Results
- [ ] Finish Section Introduction
- [ ] Write Section Conclusions
- [ ] Write Abstract in Spanish and English 


## Adittional considerations

### Structure and format

- [ ] Cover Page: Adhere strictly to the provided template.
- [ ] References to Figures and Images: Ensure they follow APA format. Carefully review all references to figures and images in the text, making sure they are correctly cited and located.
- [ ] Appendices: Additional relevant material, such as raw data or supporting documents, that complements the main content of your work but is not essential for its understanding. Supplementary external information necessary to understand certain aspects of the work, such as technical explanations or methodological details.

### Content

- [ ] Writing and Clarity: Review the work to correct any grammatical errors and ensure clear and precise communication.

### Follow a methodology

#### CRIPS-ML

**Business and Data Understanding**
- [ ] Define business objectives
- [ ] Translate business objectives into ML objectives
- [ ] Collect and verify data
- [ ] Assess the project feasibility
- [ ] Create POC

**Data Engineering**
- [ ] Feature selection
- [ ] Data selection
- [ ] Class balancing
- [ ] Cleaning data (noise reduction, data imputation)
- [ ] Feature engineering (data construction)
- [ ] Data augmentation
- [ ] Data standartization

**ML Model Engineering**
- [ ] Define quality measure of the model
- [ ] ML algorithm selection (baseline selection)
- [ ] Adding domain knowledge to specialize the model
- [ ] Model training
- [ ] Optional: applying trainsfer learning (using pre-trained models)
- [ ] Model compression
- [ ] Ensemble learning
- [ ] Documenting the ML model and experiments

**ML Model Evaluation**
- [ ] Validate model's performance
- [ ] Determine robustess
- [ ] Increase model's explainability
- [ ] Make a decision whether to deploy the model
- [ ] Document the evaluation phase

**Model Deployment**
- [ ] Evaluate model under production condition
- [ ] Assure user acceptance and usability
- [ ] Model governance
- [ ] Deploy according to the selected strategy (A/B testing, multi-armed bandits)

**Model Monitoring and Maintenance**
- [ ] Monitor the efficiency and efficacy of the model prediction serving
- [ ] Compare to the previously specified success criteria (thresholds)
- [ ] Retrain model if required
- [ ] Collect new data
- [ ] Perform labelling of the new data points
- [ ] Repeat tasks from the *Model Engineering* and *Model Evaluation* phases
- [ ] Continuous, integration, training, and deployment of the model
